services:

  Kodmit\MessengerCqrsGeneratorBundle\Command\CrudCreateCommand:
    class: Kodmit\MessengerCqrsGeneratorBundle\Command\CrudCreateCommand
    tags: ['console.command']
    arguments:
      $classFinder: "@doctrine.orm.entity_manager"